{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ciaf-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    app: ciaf
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: ciaf-vault
            port:
              number: 8000
      {{- end }}
  {{- end }}
{{- end }}
