---
apiVersion: v1
kind: Service
metadata:
  name: ciaf-vault
  namespace: ciaf
  labels:
    app: ciaf-core
    component: backend
    tier: api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: ciaf-core
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
