# GitHub Actions disabled for this repository
# All quality checks and validation are performed locally
name: Disabled Workflow
on: 
  workflow_dispatch: # Manual trigger only, will not run automatically
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "GitHub Actions disabled for this project"